#!/usr/bin/env bash

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

avahi_install() {
  declare desc="install avahi-utils"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update && apt-get -qq -y --no-install-recommends install avahi-utils
}

trigger-mdns-install() {
  declare desc="mdns install trigger"
  declare trigger="install"

  dokku_log_info1 "Setting up mdns ($DOKKU_DISTRO)"

  SCRIPT_BASE_PATH="$PLUGIN_AVAILABLE_PATH/mdns/bin"
  SCRIPT_PATH="$SCRIPT_BASE_PATH/dokku-mdns-publisher"
  SUDOERS_FILE="/etc/sudoers.d/dokku-mdns"

  case "$DOKKU_DISTRO" in
    debian | raspbian | ubuntu)
      echo "%dokku ALL=(ALL) NOPASSWD:$SCRIPT_BASE_PATH/start-service, $SCRIPT_BASE_PATH/stop-service, $SCRIPT_BASE_PATH/restart-service" >"$SUDOERS_FILE"
      if command -v avahi-utils &>/dev/null; then
        return
      fi

      avahi_install
      ;;
  esac

  if [[ $(systemctl 2>/dev/null) =~ -\.mount ]]; then
    cat <<EOF >/etc/systemd/system/dokku-mdns@.service
[Unit]
Description=Dokku MDNS service for %I
Requires=avahi-daemon.socket
After=network.target avahi-daemon.service

[Service]
Type=simple
User=dokku
ExecStart=$SCRIPT_PATH %I

[Install]
WantedBy=docker.service
EOF
  fi
}

trigger-mdns-install "$@"
