#!/usr/bin/env bash

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

trigger-mdns-post-delete() {
  declare desc="deletes an app mdns domain"
  declare trigger="post-delete"
  declare APP="$1"

  SCRIPT_PATH="$PLUGIN_AVAILABLE_PATH/mdns/bin/stop-service"

  if command -v systemctl &>/dev/null; then
    sudo "$SCRIPT_PATH" "$APP"
  fi
}

trigger-mdns-post-delete "$@"
